const cosmic = location.pathname.includes('sappho');
document.body.className = cosmic ? 'cosmic' : 'editorial';
document.title = `Hannah Zhang — ${cosmic ? 'Between worlds' : 'A practice of noticing'}`;
const photo=(name,alt,cls='',eager=false)=>`<img class="${cls}" src="assets/${encodeURI(name)}.webp" alt="${alt}" ${eager?'fetchpriority="high"':'loading="lazy"'} decoding="async">`;
const arrow=`<svg viewBox="0 0 160 100" fill="none" aria-hidden="true"><path d="M8 12C98 3 122 30 109 77M92 58l17 24 23-22" stroke="currentColor" stroke-width="2.5" stroke-linecap="round"/></svg>`;
const header=`<header><a class="wordmark" href="${cosmic?'sappho.html':'editorial.html'}" aria-label="Hannah Zhang home">h<span>z</span><sup>✳</sup></a><nav aria-label="Main navigation"><a href="#about">About</a><a href="#research">Research</a><a href="#projects">Projects</a><a href="#contact">Contact <span>↗</span></a></nav></header><div class="edition-switch" aria-label="Choose website version"><a href="editorial.html" ${!cosmic?'aria-current="page"':''}>A / Editorial</a><a href="sappho.html" ${cosmic?'aria-current="page"':''}>B / Celestial</a></div>`;
const research=`<section id="research" class="research section"><div class="section-heading"><p class="eyebrow">02 / Research</p><h2>${cosmic?'Looking closer.<br><em>Thinking further.</em>':'Small subjects.<br><em>Big questions.</em>'}</h2><p>From living systems to human signals.<br>A selection of research in progress.</p></div><div class="research-grid"><article class="research-card"><a class="image-link" href="papers/Quantification_Zebrafish_Muscle_DeepLearning.pdf" target="_blank" rel="noopener">${photo('lab/immunostaining','Fluorescence microscopy of zebrafish muscle tissue')}<span class="image-action">Read research ↗</span></a><div class="card-meta"><span>01 — Developmental biology</span><span>Smith College</span></div><h3>How does a body<br>find its form?</h3><p>Investigating Metrn / MetrnL and zebrafish development. Immunostaining, microscopy, and image analysis bring the details of muscle organization into view.</p><a class="text-link" href="papers/Quantification_Zebrafish_Muscle_DeepLearning.pdf" target="_blank" rel="noopener">Zebrafish muscle research <span>↗</span></a></article><article class="research-card second"><a class="image-link" href="papers/TalkFile_EEG-Based%20Consumer%20Preference%20Prediction%20Using%20Logistic%20Regression.pdf" target="_blank" rel="noopener">${photo('lab/whiteboard','Notes and sketches on a laboratory whiteboard')}<span class="image-action">Read presentation ↗</span></a><div class="card-meta"><span>02 — Neuroscience & computation</span><span>EEG / Python</span></div><h3>Before a choice,<br>there is a signal.</h3><p>Exploring EEG signals and consumer preference through preprocessing, statistical analysis, and logistic regression.</p><a class="text-link" href="papers/TalkFile_EEG-Based%20Consumer%20Preference%20Prediction%20Using%20Logistic%20Regression.pdf" target="_blank" rel="noopener">EEG research presentation <span>↗</span></a></article></div></section>`;
const projects=`<section id="projects" class="projects section"><div class="section-heading"><p class="eyebrow">03 / Projects & observations</p><h2>${cosmic?'Traces of being<br><em>human.</em>':'Beyond the<br><em>lab notebook.</em>'}</h2></div><div class="project-list"><article><span class="project-number">01</span><div><p class="eyebrow">HCI / An ongoing exploration</p><h3>MnemoLab</h3><p>A space for questions about memory, people, and technology.</p><details><summary>Project note <span>+</span></summary><p>My interests in neuroscience and HCI meet here: how might we design technology with more attention to the ways people remember?</p></details></div>${photo('lab-whiteboard','A personal collage of laboratory notes and everyday observations')}</article><article><span class="project-number">02</span><div><p class="eyebrow">Photography / After hours</p><h3>Looking up, slowing down.</h3><p>Star trails, city light, and moments collected between experiments.</p><details><summary>Open the field notes <span>+</span></summary><div class="mini-gallery">${photo('astronomy/star-trails','Star trails photographed above an observation site')}${photo('photograph/Seoul-540','An evening street in Seoul')}${photo('erhu/groupphoto2','Erhu ensemble group photograph')}</div><p>Photography and erhu make room for a different kind of attention.</p></details></div>${photo('astronomy/astrophotography','A silhouette observing the night sky through a telescope')}</article></div></section>`;
const footer=`<footer id="contact"><p class="eyebrow">04 / Contact</p><h2>${cosmic?'Every connection<br>begins with <em>a hello.</em>':'Something on<br>your <em>mind?</em>'}</h2><a class="email" href="mailto:hzhang29@smith.edu">hzhang29@smith.edu <span>↗</span></a><div class="footer-bottom"><span>Hannah (Zihan) Zhang · 张梓涵</span><div><a href="resume.pdf" target="_blank" rel="noopener">Résumé ↗</a><a href="https://github.com/hzhang29-droid" target="_blank" rel="noopener">GitHub ↗</a><a href="#main">Back to top ↑</a></div><span>Made of curiosity. © ${new Date().getFullYear()}</span></div></footer>`;
const editorialHero=`<section class="editorial-hero"><div class="intro"><p class="eyebrow">A personal field guide / 2026</p><h1>Hannah<br><span>Zhang</span><sup>✳</sup></h1><p class="hero-sub">A curious mind, somewhere between<br>neuroscience, code & human experience.</p><a class="text-link" href="#research">Explore my work <span>↘</span></a><span class="hand intro-note">always a work in progress.</span></div><div class="collage" aria-label="A collage of Hannah's own photographs"><span class="hand top-note">Hello, I'm Hannah!</span>${arrow}<figure class="piece portrait">${photo('life/boston-life','Hannah in Boston','',true)}<figcaption>Boston, a little while ago.</figcaption></figure><figure class="piece snow">${photo('life/hainan','Hannah in Hainan','',true)}</figure><figure class="piece film">${photo('life/new-york','Hannah in New York','',true)}</figure><span class="hand bottom-note">a few pieces of my world ↗</span><span class="collage-star" aria-hidden="true">✳</span></div><div class="hero-baseline"><span>Neuroscience + CS + HCI</span><span>Smith College · Northampton, MA</span><a href="#about">Scroll to get acquainted ↓</a></div></section><section id="about" class="about section"><div class="about-photo">${photo('lab/celebrting collaboration','Research poster presentation at Celebrating Collaborations')}<span class="hand">questions are better together.</span></div><div class="about-copy"><p class="eyebrow">01 / A little about me</p><h2>I study quiet things,<br><em>closely.</em></h2><p>I'm Hannah (Zihan) Zhang, a student at Smith College exploring neuroscience, computer science, and human–computer interaction.</p><p>I move between microscopes and code, asking how living systems develop and how technology can better understand human experience.</p><p>Outside the lab, you'll find me with a camera, an erhu, or a telescope. Different instruments; the same habit of paying attention.</p><a class="text-link" href="resume.pdf" target="_blank" rel="noopener">A little more about my path <span>↗</span></a></div></section>`;
const cosmicHero=`<section class="cosmic-hero">${photo('astronomy/field-trip-sky','A star-filled sky from Hannah’s astronomy field trip','sky',true)}<div class="nebula"></div><div class="cosmic-kicker"><span>Hannah Zhang</span><span>Neuroscience · CS · HCI</span></div><div class="cosmic-title"><p class="eyebrow">An inquiry into minds, matter & connection</p><h1>Between<br><em>worlds.</em></h1><p>From the smallest signals of life<br>to the ways we understand one another.</p><a href="#research" class="cosmic-cta">Enter the field notes <span>↓</span></a></div>${photo('astronomy/moon under telescope','The moon photographed through a telescope','moon',true)}${photo('lab/immuno on sections','Microscopy of fluorescent tissue sections','cell',true)}<div class="cosmic-caption"><span>01 / The distant & the intimate</span><p>A telescope. A microscope.<br>Two ways of learning to see.</p></div><span class="orbit-caption">Observation is where it begins.</span></section><section id="about" class="cosmic-about section"><p class="eyebrow">01 / The person behind the questions</p><div><h2>Science asks how.<br><em>I also wonder who<br>it brings us closer to.</em></h2><div class="about-columns"><p>I'm Hannah (Zihan) Zhang. At Smith College, my interests span neuroscience, computer science, and human–computer interaction.</p><p>I study development in zebrafish, explore human signals through EEG, and think about the relationships we build with technology. Beyond the lab: photography, astronomy, and erhu.</p></div><a class="text-link" href="resume.pdf" target="_blank" rel="noopener">Read my résumé <span>↗</span></a></div></section>`;
document.getElementById('site').innerHTML=header+`<main id="main">${cosmic?cosmicHero:editorialHero}${research}${projects}</main>`+footer;

// A × B: the archive on the surface, a universe underneath.
if (!cosmic) {
 document.title='Hannah Zhang — What lives underneath';
 document.querySelector('.edition-switch').remove();
 const hero=document.querySelector('.intro');
 hero.querySelector('.eyebrow').textContent='What appears on the surface / What lives underneath';
 hero.querySelector('.hero-sub').innerHTML='<span class="discipline" tabindex="0" data-world="biology">neuroscience</span> × <span class="discipline" tabindex="0" data-world="computation">computation</span><br>× <span class="discipline" tabindex="0" data-world="human">human experience</span>';
 hero.querySelector('.intro-note').textContent='there is always more underneath.';
 const collage=document.querySelector('.collage');
 collage.classList.add('reveal-surface');
 collage.insertAdjacentHTML('beforeend',`<div class="hidden-world" aria-hidden="true">${photo('astronomy/field-trip-sky','','universe-sky',true)}${photo('lab/immunostaining','','universe-tissue',true)}${photo('astronomy/moon under telescope','','universe-moon',true)}<div class="world-caption">the worlds we carry within.<small>biology · memory · connection</small></div></div><button class="reveal-toggle" type="button" aria-pressed="false">Peek underneath <span>↗</span></button>`);
 const surfaces=[collage];
 const about=document.querySelector('.about-photo');
 about.classList.add('reveal-surface');
 about.insertAdjacentHTML('beforeend',`<div class="hidden-world about-world" aria-hidden="true">${photo('astronomy/star-trails','','universe-sky')}${photo('film-contact-sheet','','about-film')}<div class="world-caption">a different kind of attention.</div></div><button class="reveal-toggle" type="button" aria-pressed="false">Another side of me ↗</button>`);
 surfaces.push(about);
 document.querySelectorAll('.research-card .image-link').forEach((el,i)=>{
  el.classList.add('reveal-surface');
  el.insertAdjacentHTML('beforeend',`<div class="hidden-world research-world" aria-hidden="true">${photo('astronomy/field-trip-sky','','universe-sky')}${photo(i===0?'lab/immuno on sections':'astronomy/star-trails','','research-inner')}<div class="world-caption">${i===0?'Life, at another scale.':'Signals become stories.'}</div></div>`);
  surfaces.push(el);
 });
 document.querySelectorAll('.project-list article').forEach((el,i)=>{
  el.classList.add('project-reveal');
  el.style.setProperty('--project-world',`url("assets/${i===0?'astronomy/star-trails':'astronomy/field-trip-sky'}.webp")`);
 });
 let frame=0;
 surfaces.forEach(el=>{
  let position={x:0,y:0};
  el.addEventListener('pointermove',e=>{
   if(e.pointerType==='touch')return;
   const r=el.getBoundingClientRect();position={x:(e.clientX-r.left)/r.width*100,y:(e.clientY-r.top)/r.height*100};
   if(frame)cancelAnimationFrame(frame);
   frame=requestAnimationFrame(()=>{el.style.setProperty('--mx',position.x+'%');el.style.setProperty('--my',position.y+'%');el.classList.add('is-peeking');frame=0;});
  });
  el.addEventListener('pointerleave',()=>{if(frame){cancelAnimationFrame(frame);frame=0}el.classList.remove('is-peeking')});
  el.addEventListener('focusin',()=>{el.style.setProperty('--mx','50%');el.style.setProperty('--my','50%');el.classList.add('is-peeking')});
  el.addEventListener('focusout',()=>el.classList.remove('is-peeking'));
  const button=el.querySelector('.reveal-toggle');
  if(button)button.addEventListener('click',()=>{const open=el.classList.toggle('is-open');button.setAttribute('aria-pressed',String(open));button.innerHTML=open?'Back to the surface <span>↙</span>':'Peek underneath <span>↗</span>'});
 });
 document.querySelectorAll('.discipline').forEach(el=>{
  const show=()=>{collage.dataset.world=el.dataset.world;collage.classList.add('word-peek');collage.style.setProperty('--mx','55%');collage.style.setProperty('--my','46%')};
  const hide=()=>{collage.classList.remove('word-peek');delete collage.dataset.world};
  el.addEventListener('pointerenter',show);el.addEventListener('pointerleave',hide);el.addEventListener('focus',show);el.addEventListener('blur',hide);
 });
 document.querySelector('.about-copy h2').classList.add('constellation-line');
 document.querySelector('.about-copy h2').tabIndex=0;
 document.querySelector('.hero-baseline>a').textContent='Move across the collage. Look a little closer ↗';
 document.querySelector('.hero-baseline>a').href='#about';
 const contact=document.querySelector('#contact');
 contact.insertAdjacentHTML('beforeend','<span class="contact-star" aria-hidden="true">✧</span>');
 contact.addEventListener('pointermove',e=>{if(e.pointerType==='touch')return;const r=contact.getBoundingClientRect();contact.style.setProperty('--cx',(e.clientX-r.left)+'px');contact.style.setProperty('--cy',(e.clientY-r.top)+'px')});
}
